# Generated by Django 4.2.6 on 2023-11-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_de_carros', '0003_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='nome',
            field=models.ManyToManyField(to='loja_de_carros.nome'),
        ),
    ]
